name: flutter_weather
description: A Flutter application to view current weather status.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  equatable: ^0.2.4
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  intl: ^0.15.8
  shared_preferences: 0.5.3+1
  geolocator: ^5.0.0
  permission_handler: ^3.1.0
  charts_flutter: ^0.6.0
  flutter_swiper : ^1.1.6
  flutter_native_splash: ^0.1.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf
